# Generated by Django 5.1.2 on 2024-10-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=50)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('date_enregistrement', models.DateField(auto_now_add=True, null=True)),
                ('poids', models.IntegerField()),
                ('sexe', models.CharField(choices=[('Male', 'M'), ('Female', 'F')], max_length=10)),
            ],
        ),
    ]
