# Generated by Django 5.0.6 on 2024-10-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=50)),
                ('date_naissance', models.DateTimeField(auto_now_add=True)),
                ('age', models.IntegerField()),
                ('poids', models.IntegerField()),
                ('sexe', models.CharField(max_length=1)),
            ],
        ),
    ]
