# Generated by Django 5.0.6 on 2024-10-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maferme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animaux',
            name='date_enregistrement',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='animaux',
            name='date_naissance',
            field=models.DateTimeField(),
        ),
    ]
